### ISSUE TITLE
Authentication Issue...

### ISSUE THREAD

**Issue by epate** [dawguk/php-garmin-connect#18] opened 2017-05-11 00:50 UTC
I'm getting the "Oops: "lt" value wasn't found in response" as was described in issue #12.

Has Garmin's authentication changed again or am I doing something wrong?

**Comment by frechina** [comment] 2017-05-11 06:35
me too, something was changed :\

**Comment by dawguk** [comment] 2017-05-11 07:45
I'll take a look and see if I can find out what's changed.

**Comment by dawguk** [comment] 2017-05-11 08:43
Sure enough, the login form has changed, and the field that was previously in the form "lt" is no longer there. I assume lt was login timeout, or something similar. I've tried manually putting an arbitrary value in there, and it's resulting in a 500 error.

The login mechanism is pretty sketchy anyway, as it was leaning on the results of sniffing the login form submission, and recreating that environment in a CURL call.

I see that tapiriik still have the same check in their code, and I have seen an issue reported that Garmin hasn't synced for some users in a while, so I wonder if this is something they are aware of.

I have tried to re-sniff the login form submission to see if the parameters being passed have changed, but the tool that I've used in the past doesn't appear to be working anymore (Tamper).

If anyone has any other clues, feel free to try them out.

**Comment by frechina** [comment] 2017-05-11 18:03
It seems the login flow is completely different.
1) POST to https://sso.garmin.com/sso/login with username, password and embed (to false)
2) GET to http://connect.garmin.com/modern?ticket=X where X is extracted from the previous step
3) GET to https://connect.garmin.com/proxy/activity-search-service-1.0/json/activities

I reached the step 3 but I can't reproduce the cookie generated in 2) and needed in 3). It is named "pin.l" and I can't get any activity without it.

Maybe this helps someone else to fix the problem

**Comment by mgnwong** [comment] 2017-05-11 19:26
Same problem here, still working on it.

**Comment by frechina** [comment] 2017-05-12 07:50
I solved the problem. Give me 5 minutes and I post it

**Comment by frechina** [comment] 2017-05-12 08:07
remove the lines 130-135 (since lt is never used)

https://github.com/dawguk/php-garmin-connect/blob/master/src/dawguk/GarminConnect.php#L130

and update the regexp of the line 138

preg_match("/ticket=([^\"]+)\"/", $strResponse, $arrMatches);

and its done!

**Comment by dawguk** [comment] 2017-05-12 08:21
Many thanks @frechina - confirmed worked, so it's merged and I'll tag for release now

**Closed by dawguk** 2017-05-12 08:21 UTC
Labels: help wanted, question

**Comment by mgnwong** [comment] 2017-05-12 16:44
Good job @frechina

**Comment by frechina** [comment] 2017-05-12 20:27
You're welcome!
